on:
  push:
    branches:
      - main

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
      - name: install ssh keys
        run: |
          mkdir -p ~/.ssh
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{secrets.SSH_HOST}} >> ~/.ssh/known_hosts

      - name: configure git to handle large files
        run: ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "
          git config --global http.postBuffer 524288000 &&
          git config --global http.maxRequestBuffer 524288000 &&
          git config --global core.compression -1"

      - name: clear git cache
        run: ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "
          cd ${{secrets.WORK_DIR}} &&
          git gc --prune=now &&
          git clean -fdx"

      - name: connect and pull
        run: ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "
          cd ${{secrets.WORK_DIR}} &&
          git checkout ${{secrets.MAIN_BRANCH}} &&
          git pull"

      - name: install composer dependencies
        run: ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "
          cd ${{secrets.WORK_DIR}} &&
          composer install --no-dev --optimize-autoloader"

      - name: cleanup
        run: rm -rf ~/.ssh
